---
name: "CI & CD"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
  release:
    types:
    - published

permissions:
  contents: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PY_VERSION: "3.11"  # Keep in sync with minimum version in pyproject.toml

jobs:
  lint:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PY_VERSION }}
    - name: Install package and linting dependencies
      run: pip install .[lint]
    - name: Check code formatting
      run: ruff format --diff
    - name: Lint code base
      run: ruff check
    - name: Check docstring formatting
      run: numpydoc lint src/peppr/*.py
    - name: Check typing
      run: mypy src

  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install build frontend
        run: pip install build
      - name: Build distribution
        run: python -m build .
      - uses: actions/upload-artifact@v4
        with:
          name: distribution
          path: ./dist/*

  test:
    name: Run tests
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: distribution
          path: dist
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install peppr and test dependencies
        # Indirection to install the wheel from glob pattern with extra dependencies
        run: |
          WHL=(dist/*.whl)
          pip install $WHL"[tests]"
      - name: Run tests
        run: pytest

  docs:
    name: Build documentation
    needs:
      - build
    runs-on: ubuntu-latest
    env:
      TMPDIR: /tmp/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: distribution
          path: dist
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install peppr and documentation dependencies
        run: |
          WHL=(dist/*.whl)
          pip install $WHL"[docs]"
      - name: Build documentation
        run: sphinx-build docs build/docs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/docs/

  publish:
    name: Upload to internal package index
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - lint
      - build
      - test
      - docs
    steps:
    - name: Checkout actions
      uses: actions/checkout@v4
      with:
        repository: aivant/actions
        token: ${{ secrets.COMPOSITE_ACTIONS_TOKEN }}
        ref: v4
        path: actions
    - uses: actions/download-artifact@v4
      with:
        name: distribution
        # Cannot use 'dist' as it would indicate to py/publish
        # that it should build the wheels itself
        path: wheelhouse
    - name: List distributions to be uploaded
      run: ls wheelhouse
    - name: Upload to internal package index
      uses: ./actions/py/publish
      with:
        sa-name: default-gha
        wheel-directory: wheelhouse

  tag:
    name: Save updated git tag
    if: github.ref == 'refs/heads/main'
    needs: publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Checkout actions
      uses: actions/checkout@v4
      with:
        repository: aivant/actions
        token: ${{ secrets.COMPOSITE_ACTIONS_TOKEN }}
        ref: v4
        path: actions
    - name: Create tag for new internal release
      uses: ./actions/git/tag
      id: get-tag
    - name: Save git tag
      if: steps.get-tag.outputs.tag-name != ''
      run: git push origin ${{ steps.get-tag.outputs.tag-name }}